# Generated by Django 4.2.7 on 2024-01-16 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloth', '0002_remove_cloth_rating_cloth_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cloth/images')),
                ('Size', models.ManyToManyField(to='cloth.size')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.category')),
                ('color', models.ManyToManyField(to='cloth.color')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloth.rating')),
            ],
        ),
    ]
