# Generated by Django 4.2.7 on 2024-01-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0003_clothwishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothwishlist',
            name='clothid',
            field=models.IntegerField(null=True),
        ),
    ]
