# Generated by Django 4.2.7 on 2024-01-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0007_alter_clothcartlist_rating_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_number',
            field=models.FloatField(default=0.0),
        ),
    ]
