# Generated by Django 4.2.7 on 2024-01-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0008_alter_rating_rating_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_number',
            field=models.IntegerField(default=0),
        ),
    ]
