# Generated by Django 4.2.7 on 2024-01-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0009_alter_rating_rating_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='clothcartlist',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='clothwishlist',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
