# Generated by Django 4.2.7 on 2024-01-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0011_clothcartlist_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothcartlist',
            name='total_price',
        ),
    ]
